export const COMPETENCIES = Object.freeze([
  {
    id: 'component-composition',
    discipline: 'React architecture',
    level: 1,
    title: 'Compose a typed product page from reusable sections',
    prerequisites: [],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'semantic-layout'],
    docs: [
      { title: 'Passing props to a component', url: 'https://react.dev/learn/passing-props-to-a-component' },
      { title: 'TypeScript JSX', url: 'https://www.typescriptlang.org/docs/handbook/jsx.html' },
    ],
    focus: 'Use typed props and reusable section components rather than one monolithic component.',
  },
  {
    id: 'responsive-layout',
    discipline: 'CSS systems',
    level: 1,
    title: 'Build an intentional responsive layout system',
    prerequisites: [],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'styles',
    appFile: 'App.jsx',
    sourceRules: ['responsive-styles'],
    docs: [
      { title: 'Responsive design', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design' },
      { title: 'CSS grid layout', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout' },
    ],
    focus: 'Create a coherent spacing, typography, grid, breakpoint and component-geometry system.',
  },
  {
    id: 'accessible-navigation',
    discipline: 'Accessibility',
    level: 2,
    title: 'Engineer typed responsive navigation',
    prerequisites: ['component-composition'],
    contractTaskId: 'responsive-site-navigation-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout'],
    docs: [
      { title: 'ARIA expanded', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-expanded' },
      { title: 'React state', url: 'https://react.dev/learn/state-a-components-memory' },
    ],
    focus: 'Implement responsive navigation whose state, keyboard behavior and landmarks remain usable across viewports.',
  },
  {
    id: 'derived-state',
    discipline: 'React state',
    level: 2,
    title: 'Model searchable derived interface state',
    prerequisites: ['component-composition'],
    contractTaskId: 'feature-lifecycle-explorer-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout'],
    docs: [
      { title: 'Choosing state structure', url: 'https://react.dev/learn/choosing-the-state-structure' },
      { title: 'You might not need an effect', url: 'https://react.dev/learn/you-might-not-need-an-effect' },
    ],
    focus: 'Keep canonical state minimal and derive filtered lifecycle content without synchronization effects.',
  },
  {
    id: 'form-validation',
    discipline: 'Forms and UX',
    level: 2,
    title: 'Build a typed accessible conversion form',
    prerequisites: ['component-composition'],
    contractTaskId: 'pricing-demo-conversion-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'React input', url: 'https://react.dev/reference/react-dom/components/input' },
      { title: 'ARIA invalid', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-invalid' },
    ],
    focus: 'Use typed form state, visible validation, accessible invalid states and an honest success transition.',
  },
  {
    id: 'design-tokens',
    discipline: 'Visual systems',
    level: 2,
    title: 'Create a durable design-token system',
    prerequisites: ['responsive-layout'],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'styles',
    appFile: 'App.jsx',
    sourceRules: ['responsive-styles'],
    docs: [
      { title: 'Using custom properties', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascading_variables/Using_CSS_custom_properties' },
      { title: 'CSS values and units', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Values_and_units' },
    ],
    focus: 'Express color, type, spacing, radii and responsive rhythm through reusable CSS custom properties.',
  },
  {
    id: 'information-architecture',
    discipline: 'Product design',
    level: 3,
    title: 'Turn dense product information into a clear journey',
    prerequisites: ['component-composition', 'responsive-layout'],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'semantic-layout'],
    docs: [
      { title: 'HTML sections and outlines', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/Heading_Elements' },
      { title: 'Landmark regions', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/landmark_role' },
    ],
    focus: 'Organize dense product content into a clear narrative, hierarchy, navigation and conversion path.',
  },
  {
    id: 'interaction-composition',
    discipline: 'Application UX',
    level: 3,
    title: 'Compose typed navigation with an accessible conversion form',
    prerequisites: ['accessible-navigation', 'form-validation'],
    contractTaskId: 'responsive-site-navigation-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'Web accessibility', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility' },
    ],
    focus: 'Keep the mastered Menu navigation working and add a real form with aria-invalid. Do not rebuild the whole event-platform showcase in one generate.',
  },
  {
    id: 'lifecycle-form-composition',
    discipline: 'Application UX',
    level: 3,
    title: 'Compose lifecycle exploration with a conversion form',
    prerequisites: ['derived-state', 'form-validation'],
    contractTaskId: 'feature-lifecycle-explorer-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'React input', url: 'https://react.dev/reference/react-dom/components/input' },
    ],
    focus: 'Keep searchable lifecycle stages working and add a real form with aria-invalid. The four-suite showcase is the capstone, not this course.',
  },
  {
    id: 'responsive-product-system',
    discipline: 'Visual systems',
    level: 3,
    title: 'Polish a complete responsive product system',
    prerequisites: ['design-tokens', 'information-architecture'],
    contractTaskId: 'event-platform-showcase-v1',
    fileMode: 'styles',
    appFile: 'App.jsx',
    sourceRules: ['responsive-styles'],
    docs: [
      { title: 'CSS container queries', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries' },
      { title: 'Responsive design', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design' },
    ],
    focus: 'Polish the complete trusted interaction scaffold into a distinctive, production-quality responsive visual system.',
  },
  {
    id: 'product-site-capstone',
    discipline: 'Capstone',
    level: 4,
    title: 'Deliver an integrated typed product-site capstone',
    prerequisites: ['interaction-composition', 'lifecycle-form-composition', 'responsive-product-system'],
    contractTaskId: 'event-platform-showcase-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'TypeScript JSX', url: 'https://www.typescriptlang.org/docs/handbook/jsx.html' },
    ],
    focus: 'Deliver a complete typed frontend that integrates information architecture, interaction, forms, accessibility and visual quality.',
  },
]);

export const CAPSTONE_CONTEXTS = Object.freeze([
  'a privacy-first analytics platform',
  'an industrial maintenance operations suite',
  'a premium developer tooling company',
  'a regional healthcare scheduling platform',
  'a sustainable logistics management product',
  'an independent creative-services marketplace',
]);

export const CAPSTONE_DIRECTIONS = Object.freeze([
  'editorial minimalism with strong typographic rhythm',
  'interface-led product storytelling with restrained motion',
  'calm enterprise clarity with evidence-first content',
  'warm human-centered design with confident conversion paths',
  'dense technical information made progressively discoverable',
]);
