export const COMPETENCIES = Object.freeze([
  {
    id: 'component-composition',
    discipline: 'React architecture',
    level: 1,
    title: 'Compose a typed product page from reusable sections',
    prerequisites: [],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'semantic-layout'],
    docs: [
      { title: 'Passing props to a component', url: 'https://react.dev/learn/passing-props-to-a-component' },
      { title: 'TypeScript JSX', url: 'https://www.typescriptlang.org/docs/handbook/jsx.html' },
    ],
    cycle: 1,
    stage: 1,
    focus: 'Use typed props and reusable section components rather than one monolithic component.',
  },
  {
    id: 'responsive-layout',
    discipline: 'CSS systems',
    level: 1,
    title: 'Build an intentional responsive layout system',
    prerequisites: [],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'styles',
    appFile: 'App.jsx',
    sourceRules: ['responsive-styles'],
    docs: [
      { title: 'Responsive design', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design' },
      { title: 'CSS grid layout', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout' },
    ],
    cycle: 1,
    stage: 1,
    focus: 'Create a coherent spacing, typography, grid, breakpoint and component-geometry system.',
  },
  {
    id: 'accessible-navigation',
    discipline: 'Accessibility',
    level: 2,
    title: 'Engineer typed responsive navigation',
    prerequisites: ['component-composition'],
    contractTaskId: 'responsive-site-navigation-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout'],
    docs: [
      { title: 'ARIA expanded', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-expanded' },
      { title: 'React state', url: 'https://react.dev/learn/state-a-components-memory' },
    ],
    cycle: 1,
    stage: 2,
    focus: 'Implement responsive navigation whose state, keyboard behavior and landmarks remain usable across viewports.',
  },
  {
    id: 'derived-state',
    discipline: 'React state',
    level: 2,
    title: 'Model searchable derived interface state',
    prerequisites: ['component-composition'],
    contractTaskId: 'feature-lifecycle-explorer-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout'],
    docs: [
      { title: 'Choosing state structure', url: 'https://react.dev/learn/choosing-the-state-structure' },
      { title: 'You might not need an effect', url: 'https://react.dev/learn/you-might-not-need-an-effect' },
    ],
    cycle: 1,
    stage: 3,
    focus: 'Keep canonical state minimal and derive filtered lifecycle content without synchronization effects.',
  },
  {
    id: 'form-validation',
    discipline: 'Forms and UX',
    level: 2,
    title: 'Build a typed accessible conversion form',
    prerequisites: ['component-composition'],
    contractTaskId: 'pricing-demo-conversion-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'React input', url: 'https://react.dev/reference/react-dom/components/input' },
      { title: 'ARIA invalid', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-invalid' },
    ],
    cycle: 1,
    stage: 3,
    focus: 'Use typed form state, visible validation, accessible invalid states and an honest success transition.',
  },
  {
    id: 'design-tokens',
    discipline: 'Visual systems',
    level: 2,
    title: 'Create a durable design-token system',
    prerequisites: ['responsive-layout'],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'styles',
    appFile: 'App.jsx',
    sourceRules: ['responsive-styles'],
    docs: [
      { title: 'Using custom properties', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascading_variables/Using_CSS_custom_properties' },
      { title: 'CSS values and units', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Values_and_units' },
    ],
    cycle: 1,
    stage: 2,
    focus: 'Express color, type, spacing, radii and responsive rhythm through reusable CSS custom properties.',
  },
  {
    id: 'information-architecture',
    discipline: 'Product design',
    level: 3,
    title: 'Turn dense product information into a clear journey',
    prerequisites: ['component-composition', 'responsive-layout'],
    contractTaskId: 'marketing-site-architecture-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'semantic-layout'],
    docs: [
      { title: 'HTML sections and outlines', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/Heading_Elements' },
      { title: 'Landmark regions', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/landmark_role' },
    ],
    cycle: 1,
    stage: 4,
    focus: 'Organize dense product content into a clear narrative, hierarchy, navigation and conversion path.',
  },
  {
    id: 'interaction-composition',
    discipline: 'Application UX',
    level: 3,
    title: 'Compose typed navigation with an accessible conversion form',
    prerequisites: ['accessible-navigation', 'form-validation'],
    contractTaskId: 'responsive-site-navigation-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'Web accessibility', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility' },
    ],
    cycle: 1,
    stage: 4,
    focus: 'Keep the mastered Menu navigation working and add a real form with aria-invalid. Do not rebuild the whole event-platform showcase in one generate.',
  },
  {
    id: 'lifecycle-form-composition',
    discipline: 'Application UX',
    level: 3,
    title: 'Compose lifecycle exploration with a conversion form',
    prerequisites: ['derived-state', 'form-validation'],
    contractTaskId: 'feature-lifecycle-explorer-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'React input', url: 'https://react.dev/reference/react-dom/components/input' },
    ],
    cycle: 1,
    stage: 5,
    focus: 'Keep searchable lifecycle stages working and add a real form with aria-invalid. The four-suite showcase is the capstone, not this course.',
  },
  {
    id: 'responsive-product-system',
    discipline: 'Visual systems',
    level: 3,
    title: 'Polish a complete responsive product system',
    prerequisites: ['design-tokens', 'information-architecture'],
    contractTaskId: 'event-platform-showcase-v1',
    fileMode: 'styles',
    appFile: 'App.jsx',
    sourceRules: ['responsive-styles'],
    docs: [
      { title: 'CSS container queries', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries' },
      { title: 'Responsive design', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design' },
    ],
    cycle: 1,
    stage: 5,
    focus: 'Polish the complete trusted interaction scaffold into a distinctive, production-quality responsive visual system.',
  },
  {
    id: 'product-site-capstone',
    discipline: 'Capstone',
    level: 4,
    title: 'Deliver an integrated typed product-site capstone',
    prerequisites: ['interaction-composition', 'lifecycle-form-composition', 'responsive-product-system'],
    contractTaskId: 'event-platform-showcase-v1',
    fileMode: 'app',
    appFile: 'App.tsx',
    sourceRules: ['typescript-component', 'react-state', 'semantic-layout', 'form-validation'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'TypeScript JSX', url: 'https://www.typescriptlang.org/docs/handbook/jsx.html' },
    ],
    cycle: 1,
    stage: 6,
    focus: 'Start from the complete typed showcase scaffold. Keep Menu nav, lifecycle explorer, packages and the Book a demo form with aria-invalid. Change copy and composition; do not delete header, main, footer or the form.',
  },
  {
    id: 'persistent-settings',
    discipline: 'Application state',
    level: 5,
    title: 'Persist typed user settings across reload',
    prerequisites: ['product-site-capstone'],
    contractTaskId: 'settings-persistence-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'React forms', url: 'https://react.dev/reference/react-dom/components/input' },
      { title: 'localStorage', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage' },
    ],
    cycle: 2,
    stage: 1,
    focus: 'Prefill from props, save to localStorage, restore after reload. This is a new exam, not another marketing site.',
  },
  {
    id: 'stateful-task-list',
    discipline: 'Stateful lists',
    level: 5,
    title: 'Manage a persistent task list with filters',
    prerequisites: ['product-site-capstone'],
    contractTaskId: 'task-list-productivity-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'Updating arrays in state', url: 'https://react.dev/learn/updating-arrays-in-state' },
      { title: 'ARIA button role', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role' },
    ],
    cycle: 2,
    stage: 2,
    focus: 'Add, toggle, delete, filter and persist tasks. Do not render a static list.',
  },
  {
    id: 'catalog-data-browsing',
    discipline: 'Data browsing',
    level: 5,
    title: 'Search, filter and sort a seeded catalog',
    prerequisites: ['product-site-capstone'],
    contractTaskId: 'catalog-search-sort-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'Rendering lists', url: 'https://react.dev/learn/rendering-lists' },
      { title: 'Select element', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select' },
    ],
    cycle: 2,
    stage: 3,
    focus: 'Compose search, category and sort over seeded products. Hardcoded catalog text fails transfer.',
  },
  {
    id: 'registration-gates',
    discipline: 'Form gates',
    level: 5,
    title: 'Validate registration before success',
    prerequisites: ['product-site-capstone'],
    contractTaskId: 'registration-validation-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state', 'form-validation'],
    docs: [
      { title: 'Controlled inputs', url: 'https://react.dev/reference/react-dom/components/input' },
      { title: 'ARIA invalid', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-invalid' },
    ],
    cycle: 2,
    stage: 4,
    focus: 'Gate Create account on name, email, password, age, invite code and terms with aria-invalid.',
  },
  {
    id: 'keyboard-dialog-a11y',
    discipline: 'Keyboard accessibility',
    level: 5,
    title: 'Keyboard tabs with a returning dialog',
    prerequisites: ['product-site-capstone'],
    contractTaskId: 'keyboard-tabs-dialog-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'React refs', url: 'https://react.dev/learn/manipulating-the-dom-with-refs' },
      { title: 'ARIA tabs', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/tab_role' },
    ],
    cycle: 2,
    stage: 5,
    focus: 'Arrow-key tabs, dialog focus trap, Escape close, focus returns to the opener.',
  },
  {
    id: 'client-routing',
    discipline: 'Application systems',
    level: 6,
    title: 'Client-route a seeded workbench',
    prerequisites: ['persistent-settings', 'stateful-task-list', 'catalog-data-browsing', 'registration-gates', 'keyboard-dialog-a11y'],
    contractTaskId: 'client-routing-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'The Location interface', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Location' },
      { title: 'hashchange', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event' },
    ],
    cycle: 3,
    stage: 1,
    focus: 'Hash routes, Not found, and browser back. This is not a marketing page.',
  },
  {
    id: 'async-data-states',
    discipline: 'Application systems',
    level: 6,
    title: 'Render loading, error, empty and ready data states',
    prerequisites: ['persistent-settings', 'stateful-task-list', 'catalog-data-browsing', 'registration-gates', 'keyboard-dialog-a11y'],
    contractTaskId: 'async-data-states-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'ARIA status', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/status_role' },
      { title: 'ARIA alert', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/alert_role' },
    ],
    cycle: 3,
    stage: 2,
    focus: 'Drive Loading/Error/Empty/Ready from Resource status. Hide seeded titles unless Ready.',
  },
  {
    id: 'error-boundary-recovery',
    discipline: 'Application systems',
    level: 6,
    title: 'Recover from a render crash behind an error boundary',
    prerequisites: ['persistent-settings', 'stateful-task-list', 'catalog-data-browsing', 'registration-gates', 'keyboard-dialog-a11y'],
    contractTaskId: 'error-boundary-recovery-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'React error boundaries', url: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary' },
      { title: 'getDerivedStateFromError', url: 'https://react.dev/reference/react/Component#static-getderivedstatefromerror' },
    ],
    cycle: 3,
    stage: 3,
    focus: 'Throw during render, show fallback, reset. Click-handler throws do not count.',
  },
  {
    id: 'large-list-performance',
    discipline: 'Application systems',
    level: 6,
    title: 'Filter a large keyed list without stalling',
    prerequisites: ['persistent-settings', 'stateful-task-list', 'catalog-data-browsing', 'registration-gates', 'keyboard-dialog-a11y'],
    contractTaskId: 'large-list-performance-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'Rendering lists', url: 'https://react.dev/learn/rendering-lists' },
      { title: 'Keeping list items in order with key', url: 'https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key' },
    ],
    cycle: 3,
    stage: 4,
    focus: 'Ninety-six unique rows, stable keys, unique search, no hung render.',
  },
  {
    id: 'react-god-workbench',
    discipline: 'God exam',
    level: 7,
    title: 'Assemble a React God workbench',
    prerequisites: ['client-routing', 'async-data-states', 'error-boundary-recovery', 'large-list-performance'],
    contractTaskId: 'react-god-workbench-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: ['react-state'],
    docs: [
      { title: 'Thinking in React', url: 'https://react.dev/learn/thinking-in-react' },
      { title: 'React error boundaries', url: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary' },
    ],
    cycle: 3,
    stage: 5,
    focus: 'One app: hash routes, data states, keyed catalog, crash recovery. Marketing showcases do not pass this exam.',
  },
  {
    id: 'visual-god',
    discipline: 'Visual systems',
    level: 8,
    title: 'Author a distinctive visual system from a seeded canvas',
    prerequisites: ['react-god-workbench'],
    contractTaskId: 'visual-god-v1',
    fileMode: 'app',
    appFile: 'App.jsx',
    sourceRules: [],
    docs: [
      { title: 'CSS custom properties', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascading_variables/Using_CSS_custom_properties' },
      { title: 'font-family', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/font-family' },
    ],
    cycle: 4,
    stage: 1,
    focus: 'The seeded visualSystem is the painted canvas. Inter, system-ui, Tailwind purple and a three-up card row fail. You judge finished frames; the examiner enforces the duk.',
  },
]);

export const PROGRAM = Object.freeze({
  id: 'frontend-mastery-v1',
  title: 'Frontend mastery ladder',
});
